// Date: 4/28/2016 2:39:23 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package org.ngs.bigx.minecraft.entity.item;

import org.ngs.bigx.minecraft.BiGX;

import net.minecraftforge.fml.common.registry.EntityRegistry;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.EntityList;
import net.minecraft.entity.EnumCreatureType;
//import net.minecraft.world.biome.BiomeGenBase;


public class ModelTank extends ModelBase
{
  //fields
    ModelRenderer tankBase;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
	
  public ModelTank()
  {
    textureWidth = 140;
    textureHeight = 80;
    
      tankBase = new ModelRenderer(this, 29, 44);
      tankBase.addBox(0F, 0F, 0F, 18, 10, 24);
      tankBase.setRotationPoint(-9F, 14F, -12F);
      tankBase.setTextureSize(140, 80);
      tankBase.mirror = true;
      setRotation(tankBase, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 74, 22);
      Shape1.addBox(0F, 0F, 0F, 10, 6, 12);
      Shape1.setRotationPoint(-5F, 8F, -6F);
      Shape1.setTextureSize(140, 80);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 37, 27);
      Shape2.addBox(0F, 0F, 0F, 2, 2, 8);
      Shape2.setRotationPoint(-1F, 10F, -14F);
      Shape2.setTextureSize(140, 80);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    tankBase.render(f5);
    Shape1.render(f5);
    Shape2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
